### ISSUE TITLE
DB-Daten auf OSM-Daten abbilden

### ISSUE THREAD

**Issue by Goldkehle** [maximilianruesch/soro-s#23]
### Description

Als AG möchte ich, dass alle DB-Daten korrekt in der OSM-Darstellung angezeigt werden.

### Acceptance Criteria
Alle Objekte (Weichen, Signale, Haltepunkte, etc.), die in den DB-Daten vorliegen, werden korrekt mit den richtigen Symbolen in der OSM-Darstellung angezeigt.

### Zu lösende Teil-Probleme

- [x] https://github.com/maximilianruesch/soro-s/issues/34
- [x] https://github.com/maximilianruesch/soro-s/issues/18
- [x] https://github.com/maximilianruesch/soro-s/issues/19
- [x] https://github.com/maximilianruesch/soro-s/issues/20
- [x] https://github.com/maximilianruesch/soro-s/issues/21
- [x] https://github.com/maximilianruesch/soro-s/issues/22

### Meta

| **Field**              |    **Value**    |
|-----------------|:------------:|
| Story ID               |           -           |
| Story Points        |           -           |
| Implemented by | *Seen in history / assignment* |
| Finished in It #   |            -           |
| Total time           |            -           |
| Velocity              |            -           |
